# Generated by Django 4.1.7 on 2023-03-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('payment', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('description', models.CharField(max_length=200, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
